# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aptitudes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atitude_description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'aptitudes',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('numeric_code', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('alpha_2_code', models.CharField(max_length=2)),
                ('alpha_3_code', models.CharField(max_length=3)),
                ('eng', models.CharField(max_length=44)),
                ('spa', models.CharField(max_length=44)),
            ],
            options={
                'db_table': 'iso_3166_1',
            },
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('degree_id', models.UUIDField(primary_key=True, serialize=False)),
                ('eng', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Licenciatura',
            },
        ),
        migrations.CreateModel(
            name='Habilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'habilidades',
            },
        ),
        migrations.CreateModel(
            name='LaboralExp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('position_functions', models.CharField(max_length=200)),
                ('laboring_since', models.DateTimeField(verbose_name='Fecha de inicio')),
                ('laboring_to', models.DateTimeField(verbose_name='Fecha fin')),
                ('at_date', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'experiencia_laboral',
            },
        ),
        migrations.CreateModel(
            name='PhoneCountryCode',
            fields=[
                ('id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('iso', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=80)),
                ('nicename', models.CharField(max_length=80)),
                ('iso3', models.CharField(max_length=3)),
                ('numcode', models.SmallIntegerField()),
                ('phonecode', models.IntegerField()),
            ],
            options={
                'db_table': 'telefono_cod_pais',
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('phoneCountryCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.PhoneCountryCode')),
            ],
            options={
                'db_table': 'telefono_numero',
            },
        ),
        migrations.CreateModel(
            name='PhoneType',
            fields=[
                ('id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('eng', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'telefono_tipo',
            },
        ),
        migrations.CreateModel(
            name='StudyHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200)),
                ('date_from', models.DateTimeField(verbose_name='Fecha de inicio')),
                ('date_to', models.DateTimeField(verbose_name='Fecha fin')),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.Degree')),
            ],
            options={
                'db_table': 'Historial_estudio',
            },
        ),
        migrations.CreateModel(
            name='StudyType',
            fields=[
                ('study_type_id', models.UUIDField(primary_key=True, serialize=False)),
                ('eng', models.CharField(max_length=200)),
                ('spa', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'grado_estudio',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_identify_number', models.UUIDField(default=0, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=200)),
                ('user_lastName', models.CharField(max_length=200)),
                ('user_born_date', models.DateTimeField(verbose_name='BirthDay Date')),
                ('user_id_identify_Type', models.IntegerField(default=0)),
                ('user_email', models.EmailField(max_length=254)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.Country')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='studyhistory',
            name='studyType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.StudyType'),
        ),
        migrations.AddField(
            model_name='studyhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.User'),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='phoneType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.PhoneType'),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.User'),
        ),
        migrations.AddField(
            model_name='laboralexp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.User'),
        ),
        migrations.AddField(
            model_name='habilities',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.User'),
        ),
        migrations.AddField(
            model_name='aptitudes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.User'),
        ),
    ]
